[phases.setup]
nixPkgs = [
  "nodejs_18",
  "libnss3",
  "libatk",
  "libatk_bridge",
  "libcups",
  "libgbm",
  "libasound2",
  "libpangocairo",
  "libxss",
  "libgtk3",
  "libxshmfence",
  "libglu"
]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = []

[phases.start]
cmd = "node hyvent.js"
