[phases.setup]
nixPkgs = [
  "nodejs_18",
  "libnss3",
  "libatk",
  "libcups",
  "libasound2",
  "libx11",
  "libxcomposite",
  "libxdamage",
  "libxrandr",
  "libgtk3",
  "libxkbcommon",
  "libxshmfence",
  "libglu",
  "libdrm",
  "libgbm"
]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = []

[phases.start]
cmd = "node hyvent.js"
